version: "3"

services:
  # runs the tests
  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      DIMP_CONFIG: "/usr/src/app/docker/config.yml"
    depends_on:
      - es
      - mongo
    volumes:
      - ./tests:/usr/src/app/tests
      - ./docker/config.yml:/usr/src/app/docker/config.yml

  # serves the docs locally with realtime auto-reloading
  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    command: mkdocs serve -f mkdocs.yml -a 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - "./docs:/usr/src/app/docs"

  es:
    image: elasticsearch:8.10.1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      cluster.name: dimp
      node.name: dimp-one
      network.bind_host: 0.0.0.0
      cluster.routing.allocation.disk.threshold_enabled: "false"
      network.host: 0.0.0.0
      # this allows us to access the cluster over http
      xpack.security.enabled: "false"
      # this ensures the tests can delete indexes using wildcards
      action.destructive_requires_name: "false"

  mongo:
    image: mongo:6.0.8
